ken_path_panner:
  ros__parameters:
    name: 
      - arm_base_to_arm_link1
      - arm_link1_to_arm_link2
      - arm_link2_to_arm_link3
      - arm_link3_to_arm_link4
      - arm_link4_to_shinai_link

    joint_num: 5
    enable_button: 4  # L1 shoulder button
    move_home_button: 3  # square button

    move_time: 0.5