<?xml version="1.0"?>

<robot name="ken" xmlns:xacro="http://ros.org/wiki/xacro">

  <xacro:include filename="$(find ken_description)/urdf/ken.xacro"/>

  <link name="world"/>                                

  <joint name="base_link_to_world_joint" type="fixed">
    <parent link="world"/>                            
    <child link="base_link"/>                         
  </joint>                                            

  <!-- The following values model the aluminum peripherial case for the
  D435 camera, with the camera joint represented by the actual
  peripherial camera tripod mount -->
  <xacro:property name="d435_cam_width" value="0.090"/>
  <xacro:property name="d435_cam_height" value="0.025"/>
  <xacro:property name="d435_cam_depth" value="0.02505"/>
  <xacro:property name="d435_cam_mount_from_center_offset" value="0.0149"/>
  <!-- glass cover is 0.1 mm inwards from front aluminium plate -->
  <xacro:property name="d435_glass_to_front" value="0.1e-3"/>
  <!-- see datasheet Revision 007, Fig. 4-4 page 65 -->
  <xacro:property name="d435_zero_depth_to_glass" value="4.2e-3"/>
  <!-- convenience precomputation to avoid clutter-->
  <xacro:property name="d435_mesh_x_offset" value="${d435_cam_mount_from_center_offset-d435_glass_to_front-d435_zero_depth_to_glass}"/>
  <!-- The following offset is relative the the physical D435 camera peripherial
  camera tripod mount -->
  <xacro:property name="d435_cam_depth_px" value="${d435_cam_mount_from_center_offset}"/>
  <xacro:property name="d435_cam_depth_py" value="0.0175"/>
  <xacro:property name="d435_cam_depth_pz" value="${d435_cam_height/2}"/>

  <link name="camera_link"/>

  <link name="camera_bottom_screw_frame"/>
  <joint name="camera_link_joint" type="fixed">
    <origin xyz="${d435_mesh_x_offset} ${d435_cam_depth_py} ${d435_cam_depth_pz}" rpy="0 0 0"/>
    <parent link="camera_bottom_screw_frame"/>
    <child link="camera_link" />
  </joint>

  <joint name="base_link_to_camera_bottom_screw_frame" type="fixed">
    <origin xyz="-0.134856 -0.07 0.381814" rpy="0 ${pi*18/180} 0"/>
    <parent link="base_link"/>                            
    <child link="camera_bottom_screw_frame"/>                         
  </joint>                                            


</robot>