ken_teleop_joy:
  ros__parameters:
    axis: [0, 1, 3, 4, -1]
    scale: [0.1, 0.1, 0.1, 0.1, 0.1]
    name: 
      - arm_base_to_arm_link1
      - arm_link1_to_arm_link2
      - arm_link2_to_arm_link3
      - arm_link3_to_arm_link4
      - arm_link4_to_shinai_link

    joint_num: 5
    enable_button: 4  # L2 shoulder button

    move_time: 0.1