vision_target_detector:
  ros__parameters:
    red_h_range_max: 10
    red_h_range_min: 170
    blue_h_range_max: 160
    blue_h_range_min: 140
    yellow_h_range_max: 35
    yellow_h_range_min: 25
    green_h_range_max: 120
    green_h_range_min: 50
    s_range_max: 255
    s_range_min: 50
    v_range_max: 255
    v_range_min: 50
    area_size_thres: 900
    depth_detection_area_thres: 600
    fx: 388.3402404785156 # camera k 0
    fy: 388.3402404785156 # camera k 4
    cx: 320.0 #321.3908386230469 # camera k 2
    cy: 240.0 #244.4134979248047 # camera k 5


